### ISSUE TITLE
Normalize exceptions in pysauropod

### ISSUE THREAD

**Issue by ianb** [mozilla/sauropod#13]
We should have a single base exception for any reasonably likely exception that pysauropod might create, including HTTPException's from 500 errors, and socket exceptions from connection refused.

**Comment by rfk** [comment]
https://github.com/mozilla/sauropod/commit/8c8bcb51aaeebb73b775f7d6e508f1f000143c48

I've added ConnectionError and ServerError, both inheriting from the base Error class.  Look ok?
(I should have done this as a pull-request for review but I forgot to do it on a branch...)

**Comment by ianb** [comment]
Yes, I think that covers it (@tarekziade ?) - though I'm not familiar with the actual library you are using the make the requests, so I'm not sure if it can throw other errors (e.g., what it throws when it gets connection refused).

**Comment by rfk** [comment]
It seems to wrap socket.error and friends in its own error classes, which all inherit from requests.exceptions.RequestException.  So I think we're safe in that regard.

**Comment by tarekziade** [comment]
Yeah that looks good to me.

**Comment by rfk** [comment]
thanks, closing
