### ISSUE TITLE
rudimentary pass on an admin page ?

### ISSUE THREAD

**Issue by dclarke** [mozilla/sauropod#4]
do a rudimentary pass at an admin page which showed number of requests, number of completed requests, number failed auth, number failed get / put requests... etc

**Comment by rfk** [comment]
Just a note that this sounds like a good use case for the metlog infrastructure being developed by services:

```
https://wiki.mozilla.org/Services/Metrics
```

**Comment by dclarke** [comment]
how about something that can come together in the next 3 hours :)

**Comment by dclarke** [comment]
j/k but from the page sounds like much is still in flux, was looking to plug something in in the short term.. and they may already be at that point, but the docs might be a bit behind
