### ISSUE TITLE
Create heartbeat response

### ISSUE THREAD

**Issue by ianb** [mozilla/sauropod#8]
We should monitor the service, so there should be some simple URL we can fetch to check that Sauropod is up and more-or-less OK

**Comment by rfk** [comment]
I started a branch with a stub /**heartbeat** page, copied from how the services pyramid apps do it:

```
https://github.com/mozilla/sauropod/tree/heartbeat-page
```

Currently it just returns "OK".  I suppose it should at least check for a live connection to hbase.

**Comment by ianb** [comment]
We were just having HBase problems, so checking it seems essential.

**Comment by rfk** [comment]
this is now in trunk, with a basic hbase-is-up-and-running check
